server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MySQL8Dialect
        format_sql=true

  kafka:
    bootstrap-servers:
      - localhost:9092
    producer:
      key-serializer:org.apache.kafka.common.serialization.StringSerializer
      value-deserializer:org.springframework.kafka.support.serializer.JsonSerializer
      acks:all
      retries:0
      batch-size:16384
      linger-ms:1
    consumer:
      group-id: my-airport-app-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer : org.springframework.kafka.support.serializer.JsonDeserializer # For receiving JSON objects
      auto-offset-reset : earliest # Start reading from the beginning if no offset is found
      enable-auto-commit: true
      auto-commit-interval: 100






